using System.ComponentModel.DataAnnotations;

namespace Spottarr.Services.Models.Categories;

/// <summary>
/// Subcategory D
/// See: https://github.com/spotnet/spotnet/wiki/Category-Codes
/// </summary>
public enum SpotnetImageGenre
{
    [Display(Name = "None")]
    None = 0,
    [Display(Name = "Action (Movies)")]
    Action = 1,
    [Display(Name = "Adventure (Movies/Books)")]
    Adventure = 2,
    [Display(Name = "Animation (Movies)")]
    Animation = 3,
    [Display(Name = "Cabaret (Movies)")]
    Cabaret = 4,
    [Display(Name = "Comedy (Movies)")]
    Comedy = 5,
    [Display(Name = "Crime (Movies/Books)")]
    Crime = 6,
    [Display(Name = "Documentary (Movies)")]
    Documentary = 7,
    [Display(Name = "Drama (Movies/Books)")]
    Drama = 8,
    [Display(Name = "Family (Movies)")]
    Family = 9,
    [Display(Name = "Fantasy (Movies/Books)")]
    Fantasy = 10,
    [Display(Name = "Arthouse (Movies)")]
    Arthouse = 11,
    [Display(Name = "Television (Movies)")]
    Television = 12,
    [Display(Name = "Horror (Movies)")]
    Horror = 13,
    [Display(Name = "Music (Movies)")]
    Music = 14,
    [Display(Name = "Musical (Movies)")]
    Musical = 15,
    [Display(Name = "Mystery (Movies/Books)")]
    Mystery = 16,
    [Display(Name = "Romance (Movies/Books)")]
    Romance = 17,
    [Display(Name = "Science Fiction (Movies/Books)")]
    ScienceFiction = 18,
    [Display(Name = "Sports (Movies)")]
    Sports = 19,
    [Display(Name = "Short (Movies)")]
    ShortMovies = 20,
    [Display(Name = "Thriller (Movies)")]
    Thriller = 21,
    [Display(Name = "War (Movies/Books)")]
    War = 22,
    [Display(Name = "Western (Movies)")]
    Western = 23,
    [Display(Name = "Other")]
    Other = 28,
    [Display(Name = "Asian (Movies)")]
    Asian = 29,
    [Display(Name = "Anime (Movies)")]
    Anime = 30,
    [Display(Name = "Cover (Books)")]
    Cover = 31,
    [Display(Name = "Comic (Books)")]
    Comic = 32,
    [Display(Name = "Cartoon (Movies)")]
    Cartoon = 33,
    [Display(Name = "Kids (Movies)")]
    Kids = 34,
    [Display(Name = "Business (Books)")]
    Business = 35,
    [Display(Name = "Computer (Books)")]
    Computer = 36,
    [Display(Name = "Hobby (Books)")]
    Hobby = 37,
    [Display(Name = "Cooking (Books)")]
    Cooking = 38,
    [Display(Name = "Knutselen (Books)")]
    Knutselen = 39,
    [Display(Name = "Handwerk (Books)")]
    Handwerk = 40,
    [Display(Name = "Health (Books)")]
    Health = 41,
    [Display(Name = "History (Movies/Books)")]
    History = 42,
    [Display(Name = "Psychology (Books)")]
    Psychology = 43,
    [Display(Name = "Newspaper (Books)")]
    Newspaper = 44,
    [Display(Name = "Magazine (Books)")]
    Magazine = 45,
    [Display(Name = "Science (Books)")]
    Science = 46,
    [Display(Name = "Woman (Books)")]
    Woman = 47,
    [Display(Name = "Religion (Books)")]
    Religion = 48,
    [Display(Name = "Roman (Books)")]
    Roman = 49,
    [Display(Name = "Biography (Books)")]
    Biography = 50,
    [Display(Name = "Detective (Movies/Books)")]
    Detective = 51,
    [Display(Name = "Animals (Movies/Books)")]
    Animals = 52,
    [Display(Name = "Travel (Books)")]
    Travel = 54,
    [Display(Name = "Non-fiction (Books)")]
    NonFiction = 56,
    [Display(Name = "Poetry (Books)")]
    Poetry = 58,
    [Display(Name = "Fairytale (Books)")]
    Fairytale = 59,
    [Display(Name = "Bi (Erotic)")]
    BiLegacy = 27,
    [Display(Name = "Lesbo (Erotic)")]
    LesboLegacy = 26,
    [Display(Name = "Homo (Erotic)")]
    HomoLegacy = 25,
    [Display(Name = "Hetero (Erotic)")]
    HeteroLegacy = 24,
    [Display(Name = "Bi (Erotic)")]
    Bi = 73,
    [Display(Name = "Lesbo (Erotic)")]
    Lesbo = 74,
    [Display(Name = "Homo (Erotic)")]
    Homo = 75,
    [Display(Name = "Hetero (Erotic)")]
    Hetero = 76,
    [Display(Name = "Amateur (Erotic)")]
    Amateur = 77,
    [Display(Name = "Group (Erotic)")]
    Group = 78,
    [Display(Name = "POV (Erotic)")]
    Pov = 79,
    [Display(Name = "Solo (Erotic)")]
    Solo = 80,
    [Display(Name = "Young (Erotic)")]
    Young = 81,
    [Display(Name = "Soft (Erotic)")]
    Soft = 82,
    [Display(Name = "Fetish (Erotic)")]
    Fetish = 83,
    [Display(Name = "Old (Erotic)")]
    Old = 84,
    [Display(Name = "BBW (Erotic)")]
    Bbw = 85,
    [Display(Name = "SM (Erotic)")]
    Sm = 86,
    [Display(Name = "Rough (Erotic)")]
    Rough = 87,
    [Display(Name = "Ebony (Erotic)")]
    Ebony = 88,
    [Display(Name = "Hentai (Erotic)")]
    Hentai = 89,
    [Display(Name = "Outdoors (Erotic)")]
    Outdoors = 90,
}