// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Spottarr.Data;

#nullable disable

namespace Spottarr.Data.PostgreSql.Migrations
{
    [DbContext(typeof(SpottarrDbContext))]
    partial class SpottarrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Spottarr.Data.Entities.FtsSpot", b =>
                {
                    b.Property<int>("SpotId")
                        .HasColumnType("integer")
                        .HasColumnName("spot_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "dutch")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Title", "Description" });

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("SpotId")
                        .HasName("pk_fts_spots");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_fts_spots_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("fts_spots", (string)null);
                });

            modelBuilder.Entity("Spottarr.Data.Entities.Spot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<int[]>("ApplicationGenres")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("application_genres");

                    b.PrimitiveCollection<int[]>("ApplicationPlatforms")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("application_platforms");

                    b.PrimitiveCollection<int[]>("ApplicationTypes")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("application_types");

                    b.PrimitiveCollection<int[]>("AudioBitrates")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("audio_bitrates");

                    b.PrimitiveCollection<int[]>("AudioFormats")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("audio_formats");

                    b.PrimitiveCollection<int[]>("AudioGenres")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("audio_genres");

                    b.PrimitiveCollection<int[]>("AudioSources")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("audio_sources");

                    b.PrimitiveCollection<int[]>("AudioTypes")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("audio_types");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<int[]>("Episodes")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("episodes");

                    b.Property<string>("Filename")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("filename");

                    b.PrimitiveCollection<int[]>("GameFormats")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("game_formats");

                    b.PrimitiveCollection<int[]>("GameGenres")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("game_genres");

                    b.PrimitiveCollection<int[]>("GamePlatforms")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("game_platforms");

                    b.PrimitiveCollection<int[]>("GameTypes")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("game_types");

                    b.PrimitiveCollection<int[]>("ImageFormats")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("image_formats");

                    b.PrimitiveCollection<int[]>("ImageGenres")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("image_genres");

                    b.PrimitiveCollection<int[]>("ImageLanguages")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("image_languages");

                    b.Property<string>("ImageMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("image_message_id");

                    b.PrimitiveCollection<int[]>("ImageSources")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("image_sources");

                    b.PrimitiveCollection<int[]>("ImageTypes")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("image_types");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("imdb_id");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("message_id");

                    b.Property<long>("MessageNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("message_number");

                    b.Property<string>("Newsgroup")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("newsgroup");

                    b.PrimitiveCollection<int[]>("NewznabCategories")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("newznab_categories");

                    b.Property<string>("NzbMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nzb_message_id");

                    b.Property<string>("ReleaseTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("release_title");

                    b.PrimitiveCollection<int[]>("Seasons")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("seasons");

                    b.Property<DateTime>("SpottedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("spotted_at");

                    b.Property<string>("Spotter")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("spotter");

                    b.Property<string>("Tag")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tag");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("TvdbId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tvdb_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("url");

                    b.PrimitiveCollection<int[]>("Years")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("years");

                    b.HasKey("Id")
                        .HasName("pk_spots");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_spots_message_id");

                    b.HasIndex("MessageNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_spots_message_number");

                    b.HasIndex("SpottedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_spots_spotted_at");

                    b.HasIndex("ImdbId", "SpottedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_spots_imdb_id_spotted_at");

                    b.HasIndex("TvdbId", "SpottedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_spots_tvdb_id_spotted_at");

                    b.ToTable("spots", (string)null);
                });

            modelBuilder.Entity("Spottarr.Data.Entities.FtsSpot", b =>
                {
                    b.HasOne("Spottarr.Data.Entities.Spot", "Spot")
                        .WithOne("FtsSpot")
                        .HasForeignKey("Spottarr.Data.Entities.FtsSpot", "SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fts_spots_spots_spot_id");

                    b.Navigation("Spot");
                });

            modelBuilder.Entity("Spottarr.Data.Entities.Spot", b =>
                {
                    b.Navigation("FtsSpot");
                });
#pragma warning restore 612, 618
        }
    }
}
